import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        
      </head>
      <body>
      <SidebarProvider>
        <AppSidebar repositoryId="ae5ea965-db92-453e-8711-338bdb65744b" />
        
          <SidebarTrigger />
          {children}
        
      </SidebarProvider>
    </body>
  </html>
  );
}
